"""Run a configured agent — CLI, MCPs, and code — entirely inside OpenShell.

Sandboxing only the MCP leaves the agent process itself on the host, which is
backwards: the configurations most worth testing are the ones granted `bash` or
`edit`, and those are exactly the ones that must not touch a developer's
machine. This module puts the whole agent inside the boundary:

* the OpenCode CLI comes from the sandbox image, not from the host;
* its MCPs are launched by OpenCode inside that same container;
* the agent's workspace is an uploaded copy, so edits are throwaway;
* provider credentials are an explicit opt-in and land outside the workspace.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .sandbox import OpenShellSandbox, SandboxError, normalize_sandbox

# Matches docker/agent-sandbox.Dockerfile. `sandbox exec` does not inherit the
# image's ENV, so these travel with every command.
AGENT_DATA_HOME = "/opt/agent/share"
AGENT_ENV = {
    "XDG_DATA_HOME": AGENT_DATA_HOME,
    "XDG_CONFIG_HOME": "/opt/agent/config",
    "XDG_CACHE_HOME": "/opt/agent/cache",
}
OPENCODE_AUTH_REMOTE = f"{AGENT_DATA_HOME}/opencode/auth.json"
PROJECT_REMOTE = "/sandbox/agent"
WORKSPACE_REMOTE = "/sandbox/workspace"
MCP_UPLOAD_ROOT = "/sandbox/mcp"

DEFAULT_AGENT_IMAGE = "docker/agent-sandbox.Dockerfile"

# OpenCode resolves `provider/model` against a catalog it fetches at startup, so
# without these it reports "Model not found" before any provider call happens.
OPENCODE_INFRA_ENDPOINTS = ["models.dev", "api.models.dev", "opencode.ai"]

# Endpoints an OpenCode run needs before it can say a single word. Used to build
# a starter egress policy; anything else the agent reaches for stays denied and
# shows up in the sandbox log as a finding.
PROVIDER_ENDPOINTS: dict[str, list[str]] = {
    "github-copilot": [
        "api.github.com",
        "api.githubcopilot.com",
        "proxy.individual.githubcopilot.com",
        "copilot-proxy.githubusercontent.com",
    ],
    "anthropic": ["api.anthropic.com"],
    "openai": ["api.openai.com"],
    "azure": ["management.azure.com"],
}


def opencode_auth_path() -> Path:
    """Where the host keeps OpenCode's provider credentials."""
    override = os.environ.get("GHOSTLAB_OPENCODE_AUTH")
    if override:
        return Path(override).expanduser()
    data_home = os.environ.get("XDG_DATA_HOME")
    root = Path(data_home).expanduser() if data_home else Path.home() / ".local" / "share"
    return root / "opencode" / "auth.json"


def provider_endpoints(model: str) -> list[str]:
    """Hosts the given ``provider/model`` needs, plus OpenCode's own catalog."""
    provider = str(model or "").split("/", 1)[0]
    return list(OPENCODE_INFRA_ENDPOINTS) + list(PROVIDER_ENDPOINTS.get(provider, []))


def render_egress_policy(hosts: list[str], binaries: "list[str] | None" = None) -> str:
    """A least-privilege OpenShell policy allowing only ``hosts`` on 443."""
    endpoints = "\n".join(
        f"      - host: {host}\n        port: 443" for host in dict.fromkeys(hosts)
    )
    binary_lines = "\n".join(
        f"      - path: {path}" for path in (binaries or ["/usr/bin/node", "/usr/bin/opencode"])
    )
    return (
        "# Generated by Ghostlab: least-privilege policy for the agent under test.\n"
        "#\n"
        "# The default policy grants no access to /opt, so the agent's data dir\n"
        "# is named explicitly. It is deliberately outside /sandbox: credentials\n"
        "# and session state must not sit in the workspace an `edit`-permitted\n"
        "# agent can read or rewrite.\n"
        "version: 1\n\n"
        "filesystem_policy:\n"
        "  include_workdir: true\n"
        "  read_only: [/usr, /lib, /proc, /dev/urandom, /app, /etc, /var/log]\n"
        "  read_write: [/sandbox, /tmp, /dev/null, /opt/agent]\n\n"
        "landlock:\n"
        "  compatibility: best_effort\n\n"
        "network_policies:\n"
        "  agent_provider:\n"
        "    name: agent-provider\n"
        "    binaries:\n"
        f"{binary_lines}\n"
        "    endpoints:\n"
        f"{endpoints}\n"
    )


def ensure_agent_policy(
    config: dict[str, Any], model: str, out_dir: Path,
    extra_hosts: "list[str] | None" = None,
) -> dict[str, Any]:
    """Give the sandbox a policy when the caller did not supply one.

    An agent needs two things the default policy denies: egress to its model
    provider, and a writable data dir outside the workspace. Generating the
    policy keeps that least-privilege rather than asking users to hand-write
    OpenShell YAML.
    """
    config = dict(config)
    if config.get("policy"):
        return config
    provider = str(model or "").split("/", 1)[0]
    if provider not in PROVIDER_ENDPOINTS:
        # The catalog hosts alone cannot serve a model, so a generated policy
        # would fail mid-run with a denial rather than up front.
        raise SandboxError(
            "sandbox_policy_missing",
            f"no known egress endpoints for provider {provider or '(unset)'!r}. "
            "Set sandbox.policy to an OpenShell policy file that allows what this "
            f"agent needs, or choose a model from: {', '.join(sorted(PROVIDER_ENDPOINTS))}.",
        )
    hosts = provider_endpoints(model) + list(extra_hosts or [])
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "agent-egress.yaml"
    path.write_text(render_egress_policy(hosts), encoding="utf-8")
    config["policy"] = str(path)
    config["network"] = "policy"
    return config


@dataclass
class AgentSandbox:
    """A live sandbox holding a configured agent, its MCPs, and its workspace."""

    sandbox: OpenShellSandbox
    project_remote: str
    workspace_remote: str
    uploads: list[dict[str, Any]]
    has_workspace: bool = False

    def remote_path(self, host_path: Any) -> str:
        """Map a host path to where it was uploaded inside the sandbox."""
        text = str(host_path)
        candidate = Path(text).expanduser()
        if not candidate.is_absolute():
            return text
        try:
            resolved = candidate.resolve()
        except OSError:
            return text
        for upload in self.uploads:
            source = Path(str(upload["source"])).resolve()
            try:
                relative = resolved.relative_to(source)
            except ValueError:
                continue
            root = Path(str(upload["target"])) / source.name
            return str(root / relative) if str(relative) != "." else str(root)
        return text

    def command(
        self, argv: list[str], *, workdir: str = "", env: "dict[str, str] | None" = None
    ) -> list[str]:
        """Wrap ``argv`` so it executes inside this sandbox."""
        return self.sandbox.ssh_command(
            argv, env=dict(env or {}), workdir=workdir or self.workspace_remote,
            base_env=dict(AGENT_ENV),
        )

    def close(self) -> None:
        self.sandbox.close()


def _credential_uploads(config: dict[str, Any]) -> list[tuple[Path, str]]:
    credentials = dict(config.get("credentials") or {})
    if not credentials.get("opencode_auth"):
        return []
    source = opencode_auth_path()
    if not source.is_file():
        raise SandboxError(
            "sandbox_credentials_missing",
            f"sandbox.credentials.opencode_auth is set but {source} does not exist. "
            "Run `opencode auth login` on the host first, or set "
            "$GHOSTLAB_OPENCODE_AUTH to the auth file.",
        )
    return [(source, OPENCODE_AUTH_REMOTE)]


def prepare_agent_sandbox(
    agent: dict[str, Any],
    sandbox_config: dict[str, Any],
    *,
    role: str = "agent",
    base_dir: "Path | None" = None,
    artifact_dir: "Path | None" = None,
    extra_paths: "list[str] | None" = None,
) -> AgentSandbox:
    """Create a sandbox containing everything the agent needs to run.

    Every host path the agent references — instruction files, skill folders,
    subagent prompts, its workspace — is uploaded, and the returned handle knows
    where each landed so commands and configs can be rewritten.
    """
    config = normalize_sandbox(sandbox_config, base_dir)
    if config.get("backend") != "openshell":
        raise SandboxError(
            "sandbox_config",
            "a configured agent must run under OpenShell; sandbox.backend is "
            f"{config.get('backend')!r}. Use backend: openshell (the agent CLI, "
            "its MCPs, and its code all execute inside the container).",
        )
    config.setdefault("image", DEFAULT_AGENT_IMAGE)
    if artifact_dir is not None:
        config["artifact_dir"] = str(artifact_dir)
        model = str((agent.get("runtime") or {}).get("model") or "")
        config = ensure_agent_policy(config, model, Path(artifact_dir))

    uploads = list(config.get("uploads") or [])
    workspace = agent.get("workspace")
    if workspace:
        source = Path(str(workspace)).expanduser()
        if not source.is_dir():
            raise SandboxError("sandbox_upload_missing", str(source))
        uploads.append({"source": str(source.resolve()), "target": WORKSPACE_REMOTE})

    for item in extra_paths or []:
        path = Path(str(item)).expanduser()
        if not path.exists():
            continue
        source = path if path.is_dir() else path.parent
        uploads.append({"source": str(source.resolve()), "target": PROJECT_REMOTE})

    # A stdio MCP is launched by OpenCode *inside* the container, so its program
    # has to be in there too — otherwise the agent's tools silently never load.
    from .sandbox import auto_uploads_for_command

    for mcp in (agent.get("inputs") or {}).get("mcps") or []:
        if str(mcp.get("transport")) != "stdio":
            continue
        connection = dict(mcp.get("connection") or {})
        raw = connection.get("command") or []
        parts = ([raw] if isinstance(raw, str) else list(raw)) + list(
            connection.get("args") or []
        )
        uploads += auto_uploads_for_command(parts, uploads, root=MCP_UPLOAD_ROOT)

    # Deduplicate while preserving order; the same skill can be referenced twice.
    seen: set[tuple[str, str]] = set()
    deduped = []
    for upload in uploads:
        key = (str(upload["source"]), str(upload["target"]))
        if key in seen:
            continue
        seen.add(key)
        deduped.append(upload)
    config["uploads"] = deduped

    credentials = _credential_uploads(config)
    sandbox = OpenShellSandbox(config, role=role)
    sandbox.create()
    try:
        for source, destination in credentials:
            sandbox.upload_file(source, destination, mode="600")
    except SandboxError:
        sandbox.close()
        raise

    workspace_remote = WORKSPACE_REMOTE
    if workspace:
        workspace_remote = f"{WORKSPACE_REMOTE}/{Path(str(workspace)).expanduser().resolve().name}"
    return AgentSandbox(
        sandbox=sandbox, project_remote=PROJECT_REMOTE,
        workspace_remote=workspace_remote, uploads=deduped,
        has_workspace=bool(workspace),
    )


def write_sandboxed_project(
    handle: AgentSandbox,
    project_dir: Path,
    agent: dict[str, Any],
    target: Any = None,
) -> str:
    """Write the OpenCode project for a sandboxed agent and push it inside.

    Paths inside the config are rewritten to their in-sandbox locations, so the
    agent reads the uploaded copies rather than host paths that do not exist in
    the container.
    """
    from .opencode_config import build_project_config

    runtime = dict(agent.get("runtime") or {})
    mcps = list((agent.get("inputs") or {}).get("mcps") or [])
    if target is not None and not mcps:
        mcps = [{
            "id": target.id, "transport": target.transport,
            "connection": target.connection,
        }]
    config = build_project_config(
        runtime, mcps, path_map=handle.remote_path,
        skills=list((agent.get("inputs") or {}).get("skills") or []),
    )
    project_dir.mkdir(parents=True, exist_ok=True)
    local = project_dir / "opencode.json"
    local.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")

    # OpenCode's --dir is both "where the config lives" and "the project the
    # agent works in". When the agent has a workspace, the config belongs *in*
    # it — otherwise the agent runs in an empty directory and cannot see the
    # code it was configured to operate on.
    remote_dir = (
        handle.workspace_remote if handle.has_workspace
        else f"{handle.project_remote}/{project_dir.name}"
    )
    handle.sandbox.upload_file(local, f"{remote_dir}/opencode.json")
    return remote_dir
