"""`rehearsal profile` — turn an inspect.json into a capability profile.

Bridges the Understand and Generate stages. Deterministic structure (tool
taxonomy by name family, read/write state surfaces, gaps) is computed locally;
a short domain summary and inferred multi-step workflows are generated by the
codex backend. Output feeds scenario generation.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .codex_backend import CodexBackend

# Schema codex must fill: domain summary, category labels, inferred workflows.
_PROFILE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "domain_summary": {"type": "string"},
        "categories": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "key": {"type": "string"},
                    "label": {"type": "string"},
                    "description": {"type": "string"},
                },
                "required": ["key", "label", "description"],
                "additionalProperties": False,
            },
        },
        "workflows": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "description": {"type": "string"},
                    "steps": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["name", "description", "steps"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["domain_summary", "categories", "workflows"],
    "additionalProperties": False,
}


def _family(name: str) -> str:
    return re.split(r"[._]", name)[0] if name else "other"


def _one_line(text: str, limit: int = 160) -> str:
    line = " ".join((text or "").split())
    return line[: limit - 3] + "..." if len(line) > limit else line


def taxonomy(tools: list[dict[str, Any]]) -> dict[str, list[str]]:
    """Group tool names by their leading name family (views_, student_, ...)."""
    groups: dict[str, list[str]] = {}
    for tool in tools:
        name = tool.get("name", "")
        if name:
            groups.setdefault(_family(name), []).append(name)
    return dict(sorted(groups.items()))


def state_surfaces(tools: list[dict[str, Any]]) -> dict[str, list[str]]:
    """Split tools into read-only vs mutating using annotations.readOnlyHint."""
    reads, writes = [], []
    for tool in tools:
        name = tool.get("name", "")
        if not name:
            continue
        read_only = bool(tool.get("annotations", {}).get("readOnlyHint"))
        (reads if read_only else writes).append(name)
    return {"read": reads, "write": writes}


def _digest(inspect: dict[str, Any]) -> str:
    """Compact, token-cheap description of the MCP for the codex prompt."""
    server = inspect.get("server_info", {})
    lines = [
        f"MCP server: {server.get('name', '?')}@{server.get('version', '?')}",
    ]
    instructions = (inspect.get("instructions") or "").strip()
    if instructions:
        lines.append(f"Server instructions: {_one_line(instructions, 400)}")
    lines.append("")
    lines.append("Tools (name | read-only? | one-line description):")
    for tool in inspect.get("tools", []):
        name = tool.get("name", "?")
        ro = "ro" if tool.get("annotations", {}).get("readOnlyHint") else "rw"
        lines.append(f"- {name} [{ro}]: {_one_line(tool.get('description', ''))}")
    lint = inspect.get("lint", [])
    if lint:
        missing = sorted({f["referenced"] for f in lint})
        lines.append("")
        lines.append(f"Note: descriptions reference these NON-EXPOSED tools: {', '.join(missing)}")
    return "\n".join(lines)


# Placeholders: {digest} {families}
PROFILE_TEMPLATE = """You are analyzing an MCP (Model Context Protocol) server to produce a capability profile.

{digest}

The tool name families present are: {families}.

Produce a JSON object with:
- domain_summary: 1-3 sentences on what this MCP is for and who would use it.
- categories: one entry per tool name family above. `key` is the family string; `label` is a short human label; `description` says what that category of tools does.
- workflows: 3-6 realistic multi-step workflows a client agent would perform with these tools. Each `steps` array lists tool names IN ORDER. Only use tool names that appear in the tool list above. Do NOT invent tools, and do not reference the non-exposed tools.

Output only the JSON object."""


def _build_prompt(digest: str, families: list[str]) -> str:
    from . import prompts

    return prompts.render(
        "profile",
        PROFILE_TEMPLATE,
        digest=digest,
        families=", ".join(families),
    )


def profile_prompt(inspect: dict[str, Any]) -> str:
    """The exact prompt that `build_capability_profile` sends to codex."""
    families = list(taxonomy(inspect.get("tools", [])).keys())
    return _build_prompt(_digest(inspect), families)


def build_capability_profile(inspect: dict[str, Any], backend: CodexBackend) -> dict[str, Any]:
    tools = inspect.get("tools", [])
    tax = taxonomy(tools)
    surfaces = state_surfaces(tools)
    families = list(tax.keys())

    generated = backend.generate_json(_build_prompt(_digest(inspect), families), _PROFILE_SCHEMA)

    tool_names = {t.get("name", "") for t in tools}
    # Drop any hallucinated steps that don't correspond to real tools.
    clean_workflows = []
    for wf in generated.get("workflows", []):
        steps = [s for s in wf.get("steps", []) if s in tool_names]
        if steps:
            clean_workflows.append({**wf, "steps": steps})

    missing_tools = sorted({f["referenced"] for f in inspect.get("lint", [])})
    write_only_no_read = []  # families that mutate but expose no read-back tool
    server = inspect.get("server_info", {})

    return {
        "mcp": f"{server.get('name', '?')}@{server.get('version', '?')}",
        "domain_summary": generated.get("domain_summary", ""),
        "taxonomy": tax,
        "categories": generated.get("categories", []),
        "state_surfaces": surfaces,
        "workflows": clean_workflows,
        "gaps": {
            "missing_referenced_tools": missing_tools,
            "write_without_readback": write_only_no_read,
        },
        "counts": {
            "tools": len(tools),
            "resources": len(inspect.get("resources", [])),
            "prompts": len(inspect.get("prompts", [])),
        },
    }


def write_profile_artifacts(profile: dict[str, Any], out_dir: Path) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    json_path = out_dir / "capabilities.json"
    md_path = out_dir / "capabilities.md"

    json_path.write_text(json.dumps(profile, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    cat_labels = {c.get("key"): c for c in profile.get("categories", [])}
    lines = [
        f"# Capability Profile: {profile.get('mcp', '?')}",
        "",
        profile.get("domain_summary", ""),
        "",
        "## Tool categories",
        "",
    ]
    for family, names in profile.get("taxonomy", {}).items():
        cat = cat_labels.get(family, {})
        label = cat.get("label", family)
        desc = cat.get("description", "")
        lines.append(f"### {label} (`{family}`)")
        if desc:
            lines.append(desc)
        lines.append(f"- tools: {', '.join(f'`{n}`' for n in names)}")
        lines.append("")

    lines += ["## Inferred workflows", ""]
    for wf in profile.get("workflows", []):
        lines.append(f"### {wf.get('name', '?')}")
        if wf.get("description"):
            lines.append(wf["description"])
        steps = " → ".join(f"`{s}`" for s in wf.get("steps", []))
        lines.append(f"- steps: {steps}")
        lines.append("")

    surfaces = profile.get("state_surfaces", {})
    lines += [
        "## State surfaces",
        "",
        f"- read-only: {', '.join(f'`{n}`' for n in surfaces.get('read', [])) or 'none'}",
        f"- mutating: {', '.join(f'`{n}`' for n in surfaces.get('write', [])) or 'none'}",
        "",
        "## Gaps",
        "",
    ]
    missing = profile.get("gaps", {}).get("missing_referenced_tools", [])
    if missing:
        lines.append(f"- descriptions reference non-exposed tools: {', '.join(f'`{m}`' for m in missing)}")
    else:
        lines.append("- none detected")
    lines.append("")

    md_path.write_text("\n".join(lines), encoding="utf-8")
    return json_path, md_path
